use pimads4
go

INSERT INTO Estados (nmEstado, dsSigla, codIbge) VALUES('Acre', 'AC', 12)
INSERT INTO Estados (nmEstado, dsSigla, codIbge) VALUES('Alagoas', 'AL', 27)
INSERT INTO Estados (nmEstado, dsSigla, codIbge) VALUES('Amazonas', 'AM', 13)
INSERT INTO Estados (nmEstado, dsSigla, codIbge) VALUES('Amapá', 'AP', 16)
INSERT INTO Estados (nmEstado, dsSigla, codIbge) VALUES('Bahia', 'BA', 29)
INSERT INTO Estados (nmEstado, dsSigla, codIbge) VALUES('Ceará', 'CE', 23)
INSERT INTO Estados (nmEstado, dsSigla, codIbge) VALUES('Distrito Federal', 'DF', 53)
INSERT INTO Estados (nmEstado, dsSigla, codIbge) VALUES('Espírito Santo', 'ES', 32)
INSERT INTO Estados (nmEstado, dsSigla, codIbge) VALUES('Goiás', 'GO', 52)
INSERT INTO Estados (nmEstado, dsSigla, codIbge) VALUES('Maranhão', 'MA', 21)
INSERT INTO Estados (nmEstado, dsSigla, codIbge) VALUES('Minas Gerais', 'MG', 31)
INSERT INTO Estados (nmEstado, dsSigla, codIbge) VALUES('Mato Grosso do Sul', 'MS', 50)
INSERT INTO Estados (nmEstado, dsSigla, codIbge) VALUES('Mato Grosso', 'MT', 51)
INSERT INTO Estados (nmEstado, dsSigla, codIbge) VALUES('Pará', 'PA', 15)
INSERT INTO Estados (nmEstado, dsSigla, codIbge) VALUES('Paraíba', 'PB', 25)
INSERT INTO Estados (nmEstado, dsSigla, codIbge) VALUES('Pernambuco', 'PE', 26)
INSERT INTO Estados (nmEstado, dsSigla, codIbge) VALUES('Piauí', 'PI', 22)
INSERT INTO Estados (nmEstado, dsSigla, codIbge) VALUES('Paraná', 'PR', 41)
INSERT INTO Estados (nmEstado, dsSigla, codIbge) VALUES('Rio de Janeiro', 'RJ', 33)
INSERT INTO Estados (nmEstado, dsSigla, codIbge) VALUES('Rio Grande do Norte', 'RN', 24)
INSERT INTO Estados (nmEstado, dsSigla, codIbge) VALUES('Rondânia', 'RO', 11)
INSERT INTO Estados (nmEstado, dsSigla, codIbge) VALUES('Roraima', 'RR', 14)
INSERT INTO Estados (nmEstado, dsSigla, codIbge) VALUES('Rio Grande do Sul', 'RS', 43)
INSERT INTO Estados (nmEstado, dsSigla, codIbge) VALUES('Santa Catarina', 'SC', 42)
INSERT INTO Estados (nmEstado, dsSigla, codIbge) VALUES('Sergipe', 'SE', 28)
INSERT INTO Estados (nmEstado, dsSigla, codIbge) VALUES('São Paulo', 'SP', 35)
INSERT INTO Estados (nmEstado, dsSigla, codIbge) VALUES('Tocantins', 'TO',17)
