use pimads4
go

INSERT INTO estado (nome, sigla, codIbge) VALUES('Acre', 'AC', 12)
INSERT INTO estado (nome, sigla, codIbge) VALUES('Alagoas', 'AL', 27)
INSERT INTO estado (nome, sigla, codIbge) VALUES('Amazonas', 'AM', 13)
INSERT INTO estado (nome, sigla, codIbge) VALUES('Amap�', 'AP', 16)
INSERT INTO estado (nome, sigla, codIbge) VALUES('Bahia', 'BA', 29)
INSERT INTO estado (nome, sigla, codIbge) VALUES('Cear�', 'CE', 23)
INSERT INTO estado (nome, sigla, codIbge) VALUES('Distrito Federal', 'DF', 53)
INSERT INTO estado (nome, sigla, codIbge) VALUES('Esp�rito Santo', 'ES', 32)
INSERT INTO estado (nome, sigla, codIbge) VALUES('Goi�s', 'GO', 52)
INSERT INTO estado (nome, sigla, codIbge) VALUES('Maranh�o', 'MA', 21)
INSERT INTO estado (nome, sigla, codIbge) VALUES('Minas Gerais', 'MG', 31)
INSERT INTO estado (nome, sigla, codIbge) VALUES('Mato Grosso do Sul', 'MS', 50)
INSERT INTO estado (nome, sigla, codIbge) VALUES('Mato Grosso', 'MT', 51)
INSERT INTO estado (nome, sigla, codIbge) VALUES('Par�', 'PA', 15)
INSERT INTO estado (nome, sigla, codIbge) VALUES('Para�ba', 'PB', 25)
INSERT INTO estado (nome, sigla, codIbge) VALUES('Pernambuco', 'PE', 26)
INSERT INTO estado (nome, sigla, codIbge) VALUES('Piau�', 'PI', 22)
INSERT INTO estado (nome, sigla, codIbge) VALUES('Paran�', 'PR', 41)
INSERT INTO estado (nome, sigla, codIbge) VALUES('Rio de Janeiro', 'RJ', 33)
INSERT INTO estado (nome, sigla, codIbge) VALUES('Rio Grande do Norte', 'RN', 24)
INSERT INTO estado (nome, sigla, codIbge) VALUES('Rond�nia', 'RO', 11)
INSERT INTO estado (nome, sigla, codIbge) VALUES('Roraima', 'RR', 14)
INSERT INTO estado (nome, sigla, codIbge) VALUES('Rio Grande do Sul', 'RS', 43)
INSERT INTO estado (nome, sigla, codIbge) VALUES('Santa Catarina', 'SC', 42)
INSERT INTO estado (nome, sigla, codIbge) VALUES('Sergipe', 'SE', 28)
INSERT INTO estado (nome, sigla, codIbge) VALUES('S�o Paulo', 'SP', 35)
INSERT INTO estado (nome, sigla, codIbge) VALUES('Tocantins', 'TO',17)
